"""update_webhook_events_schema

Revision ID: 2788f1a4ab05
Revises: b82ccf9a11ca
Create Date: 2026-08-26 13:44:33.734756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2788f1a4ab05'
down_revision: Union[str, Sequence[str], None] = 'b82ccf9a11ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('payload', sa.Text(), nullable=False))
    op.add_column('webhook_events', sa.Column('signature', sa.String(length=256), nullable=False))
    op.add_column('webhook_events', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('webhook_events', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('webhook_events', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('webhook_events', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.drop_column('webhook_events', 'received_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_column('webhook_events', 'processed_at')
    op.drop_column('webhook_events', 'created_at')
    op.drop_column('webhook_events', 'attempts')
    op.drop_column('webhook_events', 'status')
    op.drop_column('webhook_events', 'signature')
    op.drop_column('webhook_events', 'payload')
    # ### end Alembic commands ###
