"""create reconciliation tables

Revision ID: d331a169e0ae
Revises: 
Create Date: 2026-08-25 11:38:03.223570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd331a169e0ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bank_reference', sa.String(length=128), nullable=False),
    sa.Column('utr', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_reference'), 'bank_transactions', ['bank_reference'], unique=True)
    op.create_index(op.f('ix_bank_transactions_utr'), 'bank_transactions', ['utr'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_table('reconciliation_exceptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('exception_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('expected_amount', sa.BigInteger(), nullable=False),
    sa.Column('actual_amount', sa.BigInteger(), nullable=False),
    sa.Column('difference', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_exceptions_case_id'), 'reconciliation_exceptions', ['case_id'], unique=True)
    op.create_index(op.f('ix_reconciliation_exceptions_exception_type'), 'reconciliation_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_payment_id'), 'reconciliation_exceptions', ['payment_id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('settlement_id', sa.String(length=64), nullable=True),
    sa.Column('bank_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('match_type', sa.String(length=64), nullable=False),
    sa.Column('expected_amount', sa.BigInteger(), nullable=False),
    sa.Column('actual_amount', sa.BigInteger(), nullable=False),
    sa.Column('difference', sa.BigInteger(), nullable=False),
    sa.Column('reason_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_bank_transaction_id'), 'reconciliation_results', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_payment_id'), 'reconciliation_results', ['payment_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_settlement_id'), 'reconciliation_results', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_status'), 'reconciliation_results', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_razorpay_refund_id'), 'refunds', ['razorpay_refund_id'], unique=True)
    op.create_table('settlements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('razorpay_settlement_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('utr', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_payment_id'), 'settlements', ['payment_id'], unique=False)
    op.create_index(op.f('ix_settlements_razorpay_settlement_id'), 'settlements', ['razorpay_settlement_id'], unique=True)
    op.create_index(op.f('ix_settlements_utr'), 'settlements', ['utr'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_settlements_utr'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_razorpay_settlement_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_payment_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_refunds_razorpay_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_reconciliation_results_status'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_settlement_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_payment_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_bank_transaction_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_exceptions_payment_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_exception_type'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_case_id'), table_name='reconciliation_exceptions')
    op.drop_table('reconciliation_exceptions')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bank_transactions_utr'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_reference'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
