"""add settlement ledger entries

Revision ID: d727902e67e9
Revises: d331a169e0ae
Create Date: 2026-08-25 15:40:11.924285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd727902e67e9'
down_revision: Union[str, Sequence[str], None] = 'd331a169e0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('debit', sa.BigInteger(), nullable=False),
    sa.Column('credit', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_entries_entity_id'), 'settlement_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_settlement_entries_settlement_id'), 'settlement_entries', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_entries_settlement_id'), table_name='settlement_entries')
    op.drop_index(op.f('ix_settlement_entries_entity_id'), table_name='settlement_entries')
    op.drop_table('settlement_entries')
    # ### end Alembic commands ###
